// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain

// Create a RenderTexture with enableRandomWrite flag and set it
// with cs.SetTexture
RWTexture2D<float4> Result;
RWTexture2D<float4> Input;
RWTexture2D<float4> HeightMap;

uint width;
uint height;

[numthreads(8,8,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
  
    float4 input_color = Input[id.xy];   
    float4 height = HeightMap[id.xy];
    Result[id.xy] = input_color;
}
